In [1]:
# question 1
# Create a 3x3 array filled with random numbers and print its shape

In [3]:
import numpy as np
arr=np.array([[4,5,7],[1,6,9],[2,3,8]])

In [4]:
arr.shape

(3, 3)

In [6]:
# Questyion 2
# Convert an array of floate [1.1,2.2,3.3] into integer

In [7]:
arr=np.array([1.1,2.2,3.3])

In [8]:
arr_int=arr.astype(int)

In [9]:
print(arr_int)

[1 2 3]


In [10]:
# Question 3
# Use fancy indexing to extracting even number from [1,2,3,4,5,6]

In [11]:
arr=np.array([1,2,3,4,5,6])

In [15]:
even_no=[1,3,5]
print(arr[even_no])

[2 4 6]


In [17]:
# Question 4
# Reshape a 1D array of size 9 into a 3x3 matrix

In [18]:
arr=np.array([1,2,3,4,5,6,7,8,9])

In [19]:
reshaped=arr.reshape(3,3)

In [20]:
print(reshaped)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
# Question 5
# Use boolean masking to filter number greater than 50 in an array

In [22]:
arr=np.array([1,50,40,32,2,3,60,90,70,80,5])


In [23]:
greater_50=arr>50
print(arr[greater_50])

[60 90 70 80]
