In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6])

In [3]:
arr

array([1, 2, 3, 4, 5, 6])

In [4]:
#1-D ARRAY

In [5]:
arr1=np.array([10,20,30,40,50,60])

In [6]:
arr1

array([10, 20, 30, 40, 50, 60])

In [7]:
#2-D ARRAY

In [8]:
arr2=np.array([[1,2,3,4],[5,6,7,8]])

In [9]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
arr3=np.array([[1,2,3,4],[5,6,7,8]])

In [16]:
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
# Creating array from scratch

In [18]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.full((2,5),6)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [22]:
np.full((4,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [23]:
# Identity matrix

In [25]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
# Using arange methode

In [28]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [29]:
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [30]:
# linspace method

In [31]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [32]:
# Lists se array banana

In [33]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])

In [34]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [35]:
# Check array properties
# 1.Shape
# 2.Size
# 3.Dimensions
# 4.Data type

In [36]:
# 1.Shape

In [37]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [38]:
arr.shape

(3, 3)

In [39]:
# 2.Size

In [40]:
arr.size

9

In [41]:
# 3.Dimensions

In [42]:
arr.ndim

2

In [43]:
# 4.Data type

In [44]:
arr.dtype

dtype('int64')

In [45]:
# Changing data type

In [48]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]],dtype='int32')

In [49]:
arr.dtype

dtype('int32')

In [50]:
arr.astype('float64')

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [51]:
arr.dtype


dtype('int32')

In [52]:
# Reshaping array

In [54]:
arr=np.array([[1,2,3],[4,5,6]])

In [55]:
print(arr.shape)

(2, 3)


In [56]:
reshaped=arr.reshape(3,2)

In [57]:
print(reshaped)

[[1 2]
 [3 4]
 [5 6]]


In [59]:
# Convert 2D->1D array

In [60]:
flattended=arr.flatten()

In [61]:
arr

array([[1, 2, 3],
       [4, 5, 6]])