In [1]:
import numpy as np

In [2]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [3]:
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [4]:
# convert 2D->1D array

In [5]:
flate=arr.flatten()

In [6]:
print(flate)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [7]:
flate[0]

np.int64(1)

In [8]:
flate[3]

np.int64(4)

In [9]:
flate[3:6]

array([4, 5, 6])

In [10]:
flate[:5]

array([1, 2, 3, 4, 5])

In [11]:
flate[3:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [12]:
# Slicing(Extract part of an array)

In [13]:
arr=np.array([10,20,30,40,50])

In [14]:
print(arr[1:6])

[20 30 40 50]


In [15]:
print(arr[:6])

[10 20 30 40 50]


In [17]:
print(arr[: :2])#skip by 2

[10 30 50]


In [18]:
# Slicing return a view not a copy changes affect the original array

In [20]:
b=flate[3:7]

In [21]:
print(b)

[4 5 6 7]


In [22]:
b[0]=44444

In [23]:
print(b)

[44444     5     6     7]


In [24]:
print(flate)

[    1     2     3 44444     5     6     7     8     9    10    11    12]


In [25]:
# copy() mthode

In [27]:
b=flate[3:7].copy()

In [28]:
print(b)

[44444     5     6     7]


In [29]:
print(flate)

[    1     2     3 44444     5     6     7     8     9    10    11    12]


In [30]:
# Fancy indexing and boolean masking

In [31]:
arr=np.array([1,54,23,53,2,3,34,5,6])

In [35]:
idx=[1,4,6]

In [36]:
print(arr[idx])

[54  2 34]


In [42]:
idx1=arr>3
print(arr[idx1])

[54 23 53 34  5  6]


In [41]:
arr[arr>3]

array([54, 23, 53, 34,  5,  6])