In [1]:
import numpy as np

In [2]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
arr[0]

array([1, 2, 3])

In [5]:
arr[1]

array([4, 5, 6])

In [6]:
# Sum along axix crosponding to row

In [7]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [8]:
# Sum along axis crospond to  column

In [9]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [10]:
# Indexing in multi dimension array

In [11]:
arr[0][1]

np.int64(2)

In [13]:
print(arr[0,1])

2


In [14]:
print(arr[0:2,1:3])

[[2 3]
 [5 6]]


In [15]:
# Indexing in 3D array

In [16]:
arr3D=np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])

In [17]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
print(arr.shape)

(3, 3)


In [20]:
print(arr3D[0,1,2])

6


In [21]:
print(arr3D[:,0,:])

[[1 2 3]
 [7 8 9]]
